### ISSUE TITLE
Unable to load OpenID configuration for configured scheme

### ISSUE THREAD

**Issue by mynkow** [IdentityModel/IdentityModel.AspNetCore#85]
I am migrating an API to dotnet core 3.1. I also decided to start using this version of the IdentityModel. Here is the configuration of the API:

```
services.AddAuthentication(o =>
            {
                o.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                o.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(o =>
           {
               string authority = Configuration["idsrv_authority"];
               o.Authority = authority;
               o.Audience = authority + "/resources";
               o.RequireHttpsMetadata = true;
           });
```

I have other HTTP/AP/RESTI services hosted externally. I am trying to configure an HttpClient to hit one of them using client credentials. Here is my HttpClient configuration:

```
            services
                .AddHttpClient<MyHttpClient>("ng", client => client.BaseAddress = apiAddress);
            services
                .AddAccessTokenManagement(options =>
                options.Client.Clients.Add("identityserver", new ClientCredentialsTokenRequest()
                {
                    Address = $"{authority}/connect/token",
                    ClientId = clientId,
                    ClientSecret = clientSecret
                })); ;

            services.AddClientAccessTokenClient("ng", configureClient: client =>
            {
                client.BaseAddress = apiAddress;
            });
```

When I try to hit an endpoint I get the following error:
```
System.InvalidOperationException: 'Unable to load OpenID configuration for configured scheme: Object reference not set to an instance of an object.'
```
I have figured that if I add the following config and point the default challenge to "oidc" it starts doing the right thing. It tries to request a token at least.
```
.AddOpenIdConnect("oidc", o =>
             {
                 string authority = Configuration["idsrv_authority"];
                 o.Authority = authority;
                 o.ClientId = "a";
                 o.ClientSecret = "a";
             })
```

However it seems very strange to have such configuration in the startup with `AddOpenIdConnect(...)`. I already have specified to the client where is the client credentials address, the clientId and the secret inside the `ClientCredentialsTokenRequest`.

I guess I am doing something fundamentally wrong here. My question is what I have to do so that I can get an access token and hit the external API without adding `AddOpenIdConnect(...)`?

**Comment by VictorioBerra** [comment]
This might point you in the right direction: https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/master/src/AccessTokenManagement/DefaultTokenClientConfigurationService.cs#L46

You can see if theres only a single client in `_accessTokenManagementOptions.Client.Clients` it uses that, otherwise it tries to use the `AddOpenIdConnect` config.

**Comment by mynkow** [comment]
thank you @VictorioBerra 

this is exactly the case. Still it doesn't make sense. I have multiple clients and every one of them is using different configuration. With the current code in place it is not possible. What is the reason for this?

**Comment by VictorioBerra** [comment]
I think because it has no way of knowing which client to use to get the token from. 

Reading your code again, it looks like for your "ng" client you maybe need to add `.AddHttpMessageHandler` like the samples show here: https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/master/samples/TokenManagement2/Startup.cs if thats not the case, you might need to use this instead of manually adding the "ng" client https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/master/src/AccessTokenManagement/TokenManagementServiceCollectionExtensions.cs#L78

It seems to me like it should be trying to find a named client in Clients not `AccessTokenManagementDefaults.DefaultTokenClientName`.

**Comment by mynkow** [comment]
thank you again @VictorioBerra 

I figured it:

So the first step is to register the client in `AddAccessTokenManagement` which I have.

The missing piece was to add `AddClientAccessTokenHandler("ng")` to the HttpClient configuration like that:

```
services
                .AddHttpClient<NewGenClientNew>(client => client.BaseAddress = apiAddress)
                AddClientAccessTokenHandler("ng");
            services
                .AddAccessTokenManagement(options =>
                options.Client.Clients.Add("ng", new ClientCredentialsTokenRequest()
                {
                    Address = $"{authority}/connect/token",
                    ClientId = clientId,
                    ClientSecret = clientSecret
                }));
```

Now it works

**Comment by VictorioBerra** [comment]
Yep! Because:

If you do `AddClientAccessTokenHandler` then you get to set the client name that gets piped all the way to that config service we initially talked about.

IE: If you set the client name, it uses the _accessTokenManagementService and calls GetClientAccessTokenAsync which eventually uses the _tokenEndpointService and calls RequestClientAccessToken which eventually uses the _configService and calls GetClientCredentialsRequestAsync and at that point, this call will succeed https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/master/src/AccessTokenManagement/DefaultTokenClientConfigurationService.cs#L71 thanks to your code above `...options.Client.Clients.Add("ng"...`
